version: build.{build}
image: Visual Studio 2022

skip_commits:
  files:
    - docs/
    - misc/
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md

init:
- cmd: git config --global core.autocrlf true
- ps: $env:IGNORE_NORMALISATION_GIT_HEAD_MOVE = 1
- cmd: dotnet --version

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- cmd: echo "Building Tseesecake version %GitVersion_SemVer%"

build_script:
- dotnet build Tseesecake.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo

test_script:
- dotnet test Tseesecake.Testing -c Release --test-adapter-path:. --logger:Appveyor --no-build --nologo

after_test:
- ps: >-
    $ErrorActionPreference = "Stop"

    dotnet test -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=90 /p:ThresholdType=line --no-build --nologo
    
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }

- ps: >-
    $ProgressPreference = 'SilentlyContinue'
    
    Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
    
    .\codecov.exe --dir "./Tseesecake.Testing"

- dotnet pack Tseesecake -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo

artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: Q6ll0HoqlRk4OIlQM3zMGgGjjekl3E/n3h6ZT2gG37rehn+lBZdisH1ongEh3XFY
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: main