version: build.{build}
image: Visual Studio 2022

skip_commits:
  files:
    - docs/
    - misc/
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md

init:
- cmd: git config --global core.autocrlf true
- cmd: setx IGNORE_NORMALISATION_GIT_HEAD_MOVE "1"
- cmd: RefreshEnv.cmd
- pwsh: Write-Output "Target branch is '$($env:APPVEYOR_REPO_BRANCH)'"

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- cmd: dotnet nuget add source "https://nuget.pkg.github.com/Giorgi/index.json"  --name "GitHub Package for Giorgi" --username "seddryck@gmail.com" --password ("ghp"+"_fJAqlGD6rO6yvDJ8DPERb6xIVZf3bO2Tu2xA")
- pwsh: Write-Output "Building DubUrl version $($env:GitVersion_SemVer)"

build_script:
- dotnet build Tseesecake.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo

test_script:
- dotnet test Tseesecake.Testing -c Release --test-adapter-path:. --logger:Appveyor --no-build --nologo

- pwsh: |
    $ErrorActionPreference = "Stop"
    dotnet test Tseesecake.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Threshold=10 /p:ThresholdType=line --no-build --nologo
    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }

- pwsh: |
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
    .\codecov.exe --dir "./Tseesecake.Testing"

- pwsh: |
    $force = ($env:APPVEYOR_REPO_BRANCH -eq "main") #Valid for a Pull Request or a Commit on main
    & .\Tseesecake.QA\deploy-test-harness.ps1 -force:$force -config "Release" -frameworks @("net6.0") -exclude @("Drill", "Trino")
    if ($lastexitcode -gt 0) {
       throw "At least one of the test-suite was not successful. Build stopped."
    }

after_test:
- dotnet pack Tseesecake -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo

artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 11BE/qyqn1cnyYIOfJeTqtC7NoL2sN09x+OPmV6ywJ4DbVtExwNvxW5NyqKvIThP
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: main